version: "2.1"
services:
  nzbget:
    image: jscottelblein/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/nzbget:/config
      - /share/Container/nzbget-interdir:/inter-dir
      - /share/Downloads/NZBGet:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
  
  radarr:
    image: ghcr.io/linuxserver/radarr:nightly
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/radarr:/config
      - /share/Media/Movies:/Movies
      - /share/Downloads/NZBGet:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr:
    image: ghcr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/lidarr:/config
      - /share/Media/Music:/Music
      - /share/Downloads/NZBGet:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/sonarr:/config
      - /share/Media/TV:/TV
      - /share/Downloads/NZBGet:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - SUBDOMAINS=evansuk
      - TOKEN=93b12273-1dba-4b34-bbda-0babfdefcd45
      - LOG_FILE=false
    volumes:
      - /share/Container/duckdns:/config
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/changedetection:/config
    ports:
      - 5000:5000
    restart: unless-stopped

  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/openspeedtest:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped

  plex:
    image: ghcr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - VERSION=docker
    volumes:
      - /share/Container/plex:/config
      - /share/Media/TV:/TV
      - /share/Media/Movies:/Movies
      - /share/Media/Photos:/Photos
      - /share/Backups/plex_db:/db_backups
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

#  unifi-controller:
#    image: lscr.io/linuxserver/unifi-controller:latest
#    container_name: unifi-controller
#    environment:
#      - PUID=0
#      - PGID=0
#      - TZ=Europe/London
#    volumes:
#      - /share/Container/unifi:/config
#    ports:
#      - 8443:8443
#      - 3478:3478/udp
#      - 10001:10001/udp
#      - 8080:8080
#     - 1900:1900/udp #optional
#      - 8843:8843 #optional
#      - 8880:8880 #optional
#      - 5514:5514/udp #optional
#   restart: unless-stopped

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - MONGO_USER=unifi
      - MONGO_PASS=
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
      - MONGO_AUTHSOURCE= #optional
    volumes:
      - /share/Container/unifi:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      #- 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  tinfoil-hat:
    container_name: tinfoil-hat
    image: vinicioslc/tinfoil-hat:latest
    environment:
      - DEBUG=tinfoil-hat
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    ports:
      - 99:80
    volumes:
      - /share/NSW/:/games/

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8112:8112 #deluge
      - 6881:6881 #deluge
      - 6881:6881/udp #deluge
      - 8083:8083 #QbitTorrent
    volumes:
      - /share/Container/gluetun:/gluetun
      - /share/Container/deluge:/config
      - /share/Downloads/deluge:/downloads
      - /share/Container/qbittorrent:/config
      - /share/Downloads/qBittorrent:/downloads
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=mK3mAy4t3z/t1lNMuPxI0zrOGBuzZShLvu1Uj+lcpFQ=
      - WIREGUARD_ADDRESSES=10.68.162.204/32

  uxrdp:
    image: stuevansuk/ubuntuxrdp:latest
    container_name: uxrdp
    cap_add:
      - NET_ADMIN
    ports:
      - 3389:3389/tcp # HTTP proxy
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/uxrdp:/config
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    network_mode: "service:gluetun"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /share/Container/deluge:/config
      - /share/Downloads/deluge:/downloads
      - /share/NSW/:/games/
    restart: unless-stopped

  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/emby:/config
      - /share/Media/TV:/TV
      - /share/Media/Movies:/Movies
      - /share/Media/Photos:/Photos
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped