version: "2.1"
services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/nzbget:/config
      - /share/Downloads/NZBGet:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
  
  radarr:
    image: ghcr.io/linuxserver/radarr:nightly
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/radarr:/config
      - /share/Media/Movies:/Movies
      - /share/Downloads/NZBGet:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr:
    image: ghcr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/lidarr:/config
      - /share/Media/Music:/Music
      - /share/Downloads/NZBGet:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/sonarr:/config
      - /share/Media/TV:/TV
      - /share/Downloads/NZBGet:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - VERSION=docker
    volumes:
      - /share/Container/plex:/config
      - /share/Media/TV:/TV
      - /share/Media/Movies:/Movies
      - /share/Media/Photos:/Photos
      - /share/Backups/plex_db:/db_backups
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    environment:
      - TZ=Europe/London
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/Container/portainer:/data
    ports:
      - 9000:9000
      - 8000:8000
    restart: unless-stopped
