version: "2.1"
services:
  # nzbget:
  #   image: jscottelblein/nzbget:latest
  #   container_name: nzbget
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - TZ=Europe/London
  #   volumes:
  #     - /share/Container/nzbget:/config
  #     - /share/Container/nzbget-interdir:/inter-dir
  #     - /share/Downloads/NZBGet:/downloads
  #   ports:
  #     - 6789:6789
  #   restart: unless-stopped
  
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/radarr:/config
      - /share/Media/Movies:/Movies
      #- /share/Downloads/NZBGet:/downloads
      - /share/Downloads/SABnzbd/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr:
    image: ghcr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/lidarr:/config
      - /share/Media/Music:/Music
      #- /share/Downloads/NZBGet:/downloads
      - /share/Downloads/SABnzbd/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/readarr:/config
      - /share/Books:/Books
      #- /share/Downloads/NZBGet:/downloads
      - /share/Downloads/SABnzbd/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/sonarr:/config
      - /share/Media/TV:/TV
      #- /share/Downloads/NZBGet:/downloads
      - /share/Downloads/SABnzbd/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - SUBDOMAINS=evansuk
      - TOKEN=93b12273-1dba-4b34-bbda-0babfdefcd45
      - LOG_FILE=false
    volumes:
      - /share/Container/duckdns:/config
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - BASE_URL= https://changedetection.server.io/
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000
    volumes:
      - /share/Container/changedetection:/config
    ports:
      - 5000:5000
    restart: unless-stopped
  
   #playwright-chrome:
     #image: dgtlmoon/sockpuppetbrowser:latest
     #container_name: playwright-chrome
     #environment:
       #- SCREEN_WIDTH=1920
      #- SCREEN_HEIGHT=1024
      #- SCREEN_DEPTH=16
      #- ENABLE_DEBUGGER=false
      #- PREBOOT_CHROME=true
      #- CONNECTION_TIMEOUT=300000
      #- MAX_CONCURRENT_SESSIONS=10
      #- CHROME_REFRESH_TIME=600000
      #- DEFAULT_BLOCK_ADS=true
      #- DEFAULT_STEALTH=true
    #volumes:
      #- /share/Container/playwright-chrome:/config
    #ports:
      #- 3000:3000
    #restart: unless-stopped

  # openspeedtest:
  #   image: openspeedtest/latest
  #   container_name: openspeedtest
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - TZ=Europe/London
  #   volumes:
  #     - /share/Container/openspeedtest:/config
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #   restart: unless-stopped

  plex:
    image: ghcr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - VERSION=docker
    volumes:
      - /share/Container/plex:/config
      - /share/Media/TV:/TV
      - /share/Media/Movies:/Movies
      - /share/Media/Photos:/Photos
      - /share/Backups/plex_db:/db_backups
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      #- MEM_LIMIT=1024 #optional
      #- MEM_STARTUP=1024 #optional
      #- MONGO_TLS= #optional
      #- MONGO_AUTHSOURCE= #optional
    volumes:
      - /share/Container/unifi:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      #- 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

  unifi-db:
    image: docker.io/mongo:4.4
    container_name: unifi-db
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/mongodb:/data/db
      - /share/Container/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  tinfoil-hat:
    container_name: tinfoil-hat
    image: vinicioslc/tinfoil-hat:latest
    environment:
      - DEBUG=tinfoil-hat
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    ports:
      - 99:80
    volumes:
      - /share/NSW/:/games/

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8112:8112 #deluge
      - 6881:6881 #deluge
      - 6881:6881/udp #deluge
      - 8083:8083 #QbitTorrent
    volumes:
      - /share/Container/gluetun:/gluetun
      - /share/Container/deluge:/config
      - /share/Downloads/deluge:/downloads
      - /share/Container/qbittorrent:/config
      - /share/Downloads/qBittorrent:/downloads
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=wK4EvP4QrVLxmRgAciBKh3+IwlTAB/LHB/ypEB0cv28=
      - WIREGUARD_ADDRESSES=10.73.138.182/32

  # uxrdp:
  #   image: stuevansuk/ubuntuxrdp:latest
  #   container_name: uxrdp
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_ADMIN
  #   ports:
  #     - 3389:3389/tcp # RDP port
  #     - 9001:9001/tcp # Supervisord web interface
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - TZ=Europe/London
  #   volumes:
  #     - /share/Container/uxrdp/ssh:/ssh
  #     - /share/Container/uxrdp/home:/home
  #   restart: unless-stopped 

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    network_mode: "service:gluetun"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /share/Container/deluge:/config
      - /share/Downloads/deluge:/downloads
      - /share/NSW/:/nsw-games/
      - /share/PC/:/pc-games/
    restart: unless-stopped

  # qbittorrent:
  #   image: lscr.io/linuxserver/qbittorrent:latest
  #   container_name: qbittorrent
  #   network_mode: "service:gluetun"
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - TZ=Europe/London
  #     - WEBUI_PORT=8083
  #   volumes:
  #     - /share/Container/qbittorrent:/config
  #     - /share/Downloads/qBittorrent/:/downloads
  #     - /share/NSW/:/games/
  #   restart: unless-stopped

  # emby:
  #   image: lscr.io/linuxserver/emby:latest
  #   container_name: emby
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - TZ=Europe/London
  #   volumes:
  #     - /share/Container/emby:/config
  #     - /share/Media/TV:/TV
  #     - /share/Media/Movies:/Movies
  #     - /share/Media/Photos:/Photos
  #   ports:
  #     - 8096:8096
  #     - 8920:8920 #optional
  #   devices:
  #     - /dev/dri:/dev/dri #optional
  #   restart: unless-stopped

  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/pyload:/config
      - /share/Downloads/pyload/:/downloads
    ports:
      - 8000:8000
    restart: unless-stopped

  get_iplayer:
    image: ghcr.io/thespad/get_iplayer
    container_name: get_iplayer
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/get-iplayer:/config
      - /share/Downloads/iPlayer:/downloads
    ports:
      - 1935:1935
    restart: unless-stopped

  # mc:
  #   image: itzg/minecraft-bedrock-server
  #   container_name: minecraft
  #   environment:
  #     PUID: 0
  #     PGID: 0
  #     TZ: Europe/London
  #     EULA: TRUE
  #     TYPE: PAPER
  #     ENABLE_COMMAND_BLOCK: true
  #     ALLOW_CHEATS: true
  #     DEUBG: true
  #     PLUGINS: |
  #         https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
  #         https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
  #         EssentialsX-2.21.0-dev+107-7b02d22.jar
  #     CF_API_KEY: '$2a$10$8xoQagoPgHUlseyGnrIyS.rKmipdk/VECE1Z9.6KErUqn6/8Eeh46'
  #     MOTD: '§l§cEvanzSMP§r §nserver'
  #     CURSEFORGE_FILES: |
  #       geckolib
  #       aquaculture
  #       naturalist
  #       multiverse-core
  #     SPIGET_RESOURCES: 9089
  #   tty: true
  #   stdin_open: true
  #   ports:
  #     - 19132:19132/udp
  #     - 25565:25565 
  #   volumes:
  #     - /share/Container/minecraft/data:/data
  #     - /share/Container/minecraft/plugins:/plugins
  #     - /share/Container/minecraft/mods:/mods

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/sabnzbd:/config
      - /share/Downloads/SABnzbd/downloads:/downloads 
      - /share/Downloads-Scratch/SABnzbd/incomplete:/incomplete-downloads 
    ports:
      - 8085:8080
    restart: unless-stopped

  # guacamole:
  #   image: unsafetypin/guacamole
  #   container_name: guacamole
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - TZ=Europe/London
  #   volumes:
  #   - /share/Container/guacamole:/config
  #   ports:
  #   - "8086:8080"
  #   restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    ports:
      - "80:80"
    volumes:
      - /share/Container/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /share/Container/nginx/html:/usr/share/nginx/html:ro
    restart: always
  
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - /share/Container/thelounge:/var/opt/thelounge 

  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: webtop
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - TITLE=Shredtop
      - NO_DECOR=TRUE
    volumes:
      - /share/Container/webtop:/config
    ports:
      - 3000:3000
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped

  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - /share/Container/slskd/app:/app
    restart: always

  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: webtop
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /share/Container/webtop:/config
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped